[target.x86_64-pc-windows-gnu]
pre-build = [
  "apt update",
  "apt install -y clang libclang-dev nasm"
]

[target.mips-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mips-unknown-linux-gnu:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips-unknown-linux-musl]
image = "ghcr.io/cross-rs/mips-unknown-linux-musl:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mipsel-unknown-linux-gnu]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-gnu:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mipsel-unknown-linux-musl]
image = "ghcr.io/cross-rs/mipsel-unknown-linux-musl:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-gnuabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64-unknown-linux-muslabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64el-unknown-linux-gnuabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-gnuabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]

[target.mips64el-unknown-linux-muslabi64]
image = "ghcr.io/cross-rs/mips64el-unknown-linux-muslabi64:main"
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]
